"""change name

Revision ID: 7afa77e349fc
Revises: 01a164018740
Create Date: 2020-10-30 17:31:02.585702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afa77e349fc'
down_revision = '01a164018740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('title', sa.Text(), nullable=True))
    op.drop_column('todolists', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('todolists', 'title')
    # ### end Alembic commands ###
